Update resolver to 18.28
I wanted to update to 19.1, but many packages fail to compile on my M1 Mac:

    > fatal error: 'ffitarget_arm64.h' file not found

Resolver 18.28 is relatively recent and works on my M1 Mac.